app = "my-little-blog"

[build]
dockerfile = "Dockerfile"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0

[http_service.concurrency]
type = "connections"
hard_limit = 25
soft_limit = 20

[http_service.http_checks]
interval = "10s"
timeout = "2s"
grace_period = "5s"
method = "get"
path = "/health"
protocol = "http"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256

[env]
PORT = "8080"

# Ensure only single instance deployment
[deploy]
strategy = "immediate"
release_command = ""
auto_rollback = true

# Force specific regions
[regions]
only = ["ams"]
